// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"reflect"
	"testing"

	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/randomize"
	"github.com/volatiletech/sqlboiler/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testBasicTrades(t *testing.T) {
	t.Parallel()

	query := BasicTrades()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testBasicTradesDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &BasicTrade{}
	if err = randomize.Struct(seed, o, basicTradeDBTypes, true, basicTradeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BasicTrade struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := BasicTrades().Count(tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testBasicTradesQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &BasicTrade{}
	if err = randomize.Struct(seed, o, basicTradeDBTypes, true, basicTradeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BasicTrade struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := BasicTrades().DeleteAll(tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := BasicTrades().Count(tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testBasicTradesSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &BasicTrade{}
	if err = randomize.Struct(seed, o, basicTradeDBTypes, true, basicTradeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BasicTrade struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := BasicTradeSlice{o}

	if rowsAff, err := slice.DeleteAll(tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := BasicTrades().Count(tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testBasicTradesExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &BasicTrade{}
	if err = randomize.Struct(seed, o, basicTradeDBTypes, true, basicTradeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BasicTrade struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := BasicTradeExists(tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if BasicTrade exists: %s", err)
	}
	if !e {
		t.Errorf("Expected BasicTradeExists to return true, but got false.")
	}
}

func testBasicTradesFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &BasicTrade{}
	if err = randomize.Struct(seed, o, basicTradeDBTypes, true, basicTradeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BasicTrade struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	basicTradeFound, err := FindBasicTrade(tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if basicTradeFound == nil {
		t.Error("want a record, got nil")
	}
}

func testBasicTradesBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &BasicTrade{}
	if err = randomize.Struct(seed, o, basicTradeDBTypes, true, basicTradeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BasicTrade struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = BasicTrades().Bind(nil, tx, o); err != nil {
		t.Error(err)
	}
}

func testBasicTradesOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &BasicTrade{}
	if err = randomize.Struct(seed, o, basicTradeDBTypes, true, basicTradeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BasicTrade struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := BasicTrades().One(tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testBasicTradesAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	basicTradeOne := &BasicTrade{}
	basicTradeTwo := &BasicTrade{}
	if err = randomize.Struct(seed, basicTradeOne, basicTradeDBTypes, false, basicTradeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BasicTrade struct: %s", err)
	}
	if err = randomize.Struct(seed, basicTradeTwo, basicTradeDBTypes, false, basicTradeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BasicTrade struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = basicTradeOne.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = basicTradeTwo.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := BasicTrades().All(tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testBasicTradesCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	basicTradeOne := &BasicTrade{}
	basicTradeTwo := &BasicTrade{}
	if err = randomize.Struct(seed, basicTradeOne, basicTradeDBTypes, false, basicTradeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BasicTrade struct: %s", err)
	}
	if err = randomize.Struct(seed, basicTradeTwo, basicTradeDBTypes, false, basicTradeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BasicTrade struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = basicTradeOne.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = basicTradeTwo.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := BasicTrades().Count(tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func testBasicTradesInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &BasicTrade{}
	if err = randomize.Struct(seed, o, basicTradeDBTypes, true, basicTradeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BasicTrade struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := BasicTrades().Count(tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testBasicTradesInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &BasicTrade{}
	if err = randomize.Struct(seed, o, basicTradeDBTypes, true); err != nil {
		t.Errorf("Unable to randomize BasicTrade struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Whitelist(basicTradeColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := BasicTrades().Count(tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testBasicTradeToManyClaims(t *testing.T) {
	var err error

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()

	var a BasicTrade
	var b, c Claim

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, basicTradeDBTypes, true, basicTradeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BasicTrade struct: %s", err)
	}

	if err := a.Insert(tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = randomize.Struct(seed, &b, claimDBTypes, false, claimColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, claimDBTypes, false, claimColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}

	b.BasicTradeID = a.ID
	c.BasicTradeID = a.ID

	if err = b.Insert(tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := a.Claims().All(tx)
	if err != nil {
		t.Fatal(err)
	}

	bFound, cFound := false, false
	for _, v := range check {
		if v.BasicTradeID == b.BasicTradeID {
			bFound = true
		}
		if v.BasicTradeID == c.BasicTradeID {
			cFound = true
		}
	}

	if !bFound {
		t.Error("expected to find b")
	}
	if !cFound {
		t.Error("expected to find c")
	}

	slice := BasicTradeSlice{&a}
	if err = a.L.LoadClaims(tx, false, (*[]*BasicTrade)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.Claims); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	a.R.Claims = nil
	if err = a.L.LoadClaims(tx, true, &a, nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.Claims); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	if t.Failed() {
		t.Logf("%#v", check)
	}
}

func testBasicTradeToManyTrades(t *testing.T) {
	var err error

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()

	var a BasicTrade
	var b, c Trade

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, basicTradeDBTypes, true, basicTradeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BasicTrade struct: %s", err)
	}

	if err := a.Insert(tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = randomize.Struct(seed, &b, tradeDBTypes, false, tradeColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, tradeDBTypes, false, tradeColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}

	b.BasicTradeID = a.ID
	c.BasicTradeID = a.ID

	if err = b.Insert(tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := a.Trades().All(tx)
	if err != nil {
		t.Fatal(err)
	}

	bFound, cFound := false, false
	for _, v := range check {
		if v.BasicTradeID == b.BasicTradeID {
			bFound = true
		}
		if v.BasicTradeID == c.BasicTradeID {
			cFound = true
		}
	}

	if !bFound {
		t.Error("expected to find b")
	}
	if !cFound {
		t.Error("expected to find c")
	}

	slice := BasicTradeSlice{&a}
	if err = a.L.LoadTrades(tx, false, (*[]*BasicTrade)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.Trades); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	a.R.Trades = nil
	if err = a.L.LoadTrades(tx, true, &a, nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.Trades); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	if t.Failed() {
		t.Logf("%#v", check)
	}
}

func testBasicTradeToManyAddOpClaims(t *testing.T) {
	var err error

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()

	var a BasicTrade
	var b, c, d, e Claim

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, basicTradeDBTypes, false, strmangle.SetComplement(basicTradePrimaryKeyColumns, basicTradeColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*Claim{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, claimDBTypes, false, strmangle.SetComplement(claimPrimaryKeyColumns, claimColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	foreignersSplitByInsertion := [][]*Claim{
		{&b, &c},
		{&d, &e},
	}

	for i, x := range foreignersSplitByInsertion {
		err = a.AddClaims(tx, i != 0, x...)
		if err != nil {
			t.Fatal(err)
		}

		first := x[0]
		second := x[1]

		if a.ID != first.BasicTradeID {
			t.Error("foreign key was wrong value", a.ID, first.BasicTradeID)
		}
		if a.ID != second.BasicTradeID {
			t.Error("foreign key was wrong value", a.ID, second.BasicTradeID)
		}

		if first.R.BasicTrade != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}
		if second.R.BasicTrade != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}

		if a.R.Claims[i*2] != first {
			t.Error("relationship struct slice not set to correct value")
		}
		if a.R.Claims[i*2+1] != second {
			t.Error("relationship struct slice not set to correct value")
		}

		count, err := a.Claims().Count(tx)
		if err != nil {
			t.Fatal(err)
		}
		if want := int64((i + 1) * 2); count != want {
			t.Error("want", want, "got", count)
		}
	}
}
func testBasicTradeToManyAddOpTrades(t *testing.T) {
	var err error

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()

	var a BasicTrade
	var b, c, d, e Trade

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, basicTradeDBTypes, false, strmangle.SetComplement(basicTradePrimaryKeyColumns, basicTradeColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*Trade{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, tradeDBTypes, false, strmangle.SetComplement(tradePrimaryKeyColumns, tradeColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	foreignersSplitByInsertion := [][]*Trade{
		{&b, &c},
		{&d, &e},
	}

	for i, x := range foreignersSplitByInsertion {
		err = a.AddTrades(tx, i != 0, x...)
		if err != nil {
			t.Fatal(err)
		}

		first := x[0]
		second := x[1]

		if a.ID != first.BasicTradeID {
			t.Error("foreign key was wrong value", a.ID, first.BasicTradeID)
		}
		if a.ID != second.BasicTradeID {
			t.Error("foreign key was wrong value", a.ID, second.BasicTradeID)
		}

		if first.R.BasicTrade != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}
		if second.R.BasicTrade != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}

		if a.R.Trades[i*2] != first {
			t.Error("relationship struct slice not set to correct value")
		}
		if a.R.Trades[i*2+1] != second {
			t.Error("relationship struct slice not set to correct value")
		}

		count, err := a.Trades().Count(tx)
		if err != nil {
			t.Fatal(err)
		}
		if want := int64((i + 1) * 2); count != want {
			t.Error("want", want, "got", count)
		}
	}
}

func testBasicTradesReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &BasicTrade{}
	if err = randomize.Struct(seed, o, basicTradeDBTypes, true, basicTradeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BasicTrade struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(tx); err != nil {
		t.Error(err)
	}
}

func testBasicTradesReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &BasicTrade{}
	if err = randomize.Struct(seed, o, basicTradeDBTypes, true, basicTradeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BasicTrade struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := BasicTradeSlice{o}

	if err = slice.ReloadAll(tx); err != nil {
		t.Error(err)
	}
}

func testBasicTradesSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &BasicTrade{}
	if err = randomize.Struct(seed, o, basicTradeDBTypes, true, basicTradeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BasicTrade struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := BasicTrades().All(tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	basicTradeDBTypes = map[string]string{`ID`: `int`, `Name`: `varchar`, `Created`: `datetime`, `Updated`: `datetime`, `IsDeleted`: `bit`}
	_                 = bytes.MinRead
)

func testBasicTradesUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(basicTradePrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(basicTradeAllColumns) == len(basicTradePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &BasicTrade{}
	if err = randomize.Struct(seed, o, basicTradeDBTypes, true, basicTradeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BasicTrade struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := BasicTrades().Count(tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, basicTradeDBTypes, true, basicTradePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize BasicTrade struct: %s", err)
	}

	if rowsAff, err := o.Update(tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testBasicTradesSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(basicTradeAllColumns) == len(basicTradePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &BasicTrade{}
	if err = randomize.Struct(seed, o, basicTradeDBTypes, true, basicTradeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BasicTrade struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := BasicTrades().Count(tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, basicTradeDBTypes, true, basicTradePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize BasicTrade struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(basicTradeAllColumns, basicTradePrimaryKeyColumns) {
		fields = basicTradeAllColumns
	} else {
		fields = strmangle.SetComplement(
			basicTradeAllColumns,
			basicTradePrimaryKeyColumns,
		)
		fields = strmangle.SetComplement(
			fields,
			basicTradeColumnsWithAuto,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := BasicTradeSlice{o}
	if rowsAff, err := slice.UpdateAll(tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testBasicTradesUpsert(t *testing.T) {
	t.Parallel()

	if len(basicTradeAllColumns) == len(basicTradePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := BasicTrade{}
	if err = randomize.Struct(seed, &o, basicTradeDBTypes, true); err != nil {
		t.Errorf("Unable to randomize BasicTrade struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert BasicTrade: %s", err)
	}

	count, err := BasicTrades().Count(tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, basicTradeDBTypes, false, basicTradePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize BasicTrade struct: %s", err)
	}

	if err = o.Upsert(tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert BasicTrade: %s", err)
	}

	count, err = BasicTrades().Count(tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
