// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	BasicTrades    string
	ClaimHistories string
	Claims         string
	Profiles       string
	Projects       string
	Roles          string
	Trades         string
	Users          string
}{
	BasicTrades:    "basic_trades",
	ClaimHistories: "claim_histories",
	Claims:         "claims",
	Profiles:       "profiles",
	Projects:       "projects",
	Roles:          "roles",
	Trades:         "trades",
	Users:          "users",
}
