// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"reflect"
	"testing"

	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/randomize"
	"github.com/volatiletech/sqlboiler/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testTradeCategories(t *testing.T) {
	t.Parallel()

	query := TradeCategories()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testTradeCategoriesDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &TradeCategory{}
	if err = randomize.Struct(seed, o, tradeCategoryDBTypes, true, tradeCategoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TradeCategory struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := TradeCategories().Count(tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testTradeCategoriesQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &TradeCategory{}
	if err = randomize.Struct(seed, o, tradeCategoryDBTypes, true, tradeCategoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TradeCategory struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := TradeCategories().DeleteAll(tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := TradeCategories().Count(tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testTradeCategoriesSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &TradeCategory{}
	if err = randomize.Struct(seed, o, tradeCategoryDBTypes, true, tradeCategoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TradeCategory struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := TradeCategorySlice{o}

	if rowsAff, err := slice.DeleteAll(tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := TradeCategories().Count(tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testTradeCategoriesExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &TradeCategory{}
	if err = randomize.Struct(seed, o, tradeCategoryDBTypes, true, tradeCategoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TradeCategory struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := TradeCategoryExists(tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if TradeCategory exists: %s", err)
	}
	if !e {
		t.Errorf("Expected TradeCategoryExists to return true, but got false.")
	}
}

func testTradeCategoriesFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &TradeCategory{}
	if err = randomize.Struct(seed, o, tradeCategoryDBTypes, true, tradeCategoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TradeCategory struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	tradeCategoryFound, err := FindTradeCategory(tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if tradeCategoryFound == nil {
		t.Error("want a record, got nil")
	}
}

func testTradeCategoriesBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &TradeCategory{}
	if err = randomize.Struct(seed, o, tradeCategoryDBTypes, true, tradeCategoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TradeCategory struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = TradeCategories().Bind(nil, tx, o); err != nil {
		t.Error(err)
	}
}

func testTradeCategoriesOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &TradeCategory{}
	if err = randomize.Struct(seed, o, tradeCategoryDBTypes, true, tradeCategoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TradeCategory struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := TradeCategories().One(tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testTradeCategoriesAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	tradeCategoryOne := &TradeCategory{}
	tradeCategoryTwo := &TradeCategory{}
	if err = randomize.Struct(seed, tradeCategoryOne, tradeCategoryDBTypes, false, tradeCategoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TradeCategory struct: %s", err)
	}
	if err = randomize.Struct(seed, tradeCategoryTwo, tradeCategoryDBTypes, false, tradeCategoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TradeCategory struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = tradeCategoryOne.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = tradeCategoryTwo.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := TradeCategories().All(tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testTradeCategoriesCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	tradeCategoryOne := &TradeCategory{}
	tradeCategoryTwo := &TradeCategory{}
	if err = randomize.Struct(seed, tradeCategoryOne, tradeCategoryDBTypes, false, tradeCategoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TradeCategory struct: %s", err)
	}
	if err = randomize.Struct(seed, tradeCategoryTwo, tradeCategoryDBTypes, false, tradeCategoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TradeCategory struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = tradeCategoryOne.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = tradeCategoryTwo.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := TradeCategories().Count(tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func testTradeCategoriesInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &TradeCategory{}
	if err = randomize.Struct(seed, o, tradeCategoryDBTypes, true, tradeCategoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TradeCategory struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := TradeCategories().Count(tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testTradeCategoriesInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &TradeCategory{}
	if err = randomize.Struct(seed, o, tradeCategoryDBTypes, true); err != nil {
		t.Errorf("Unable to randomize TradeCategory struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Whitelist(tradeCategoryColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := TradeCategories().Count(tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testTradeCategoryToManyClaims(t *testing.T) {
	var err error

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()

	var a TradeCategory
	var b, c Claim

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, tradeCategoryDBTypes, true, tradeCategoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TradeCategory struct: %s", err)
	}

	if err := a.Insert(tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = randomize.Struct(seed, &b, claimDBTypes, false, claimColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, claimDBTypes, false, claimColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}

	b.TradeCategoryID = a.ID
	c.TradeCategoryID = a.ID

	if err = b.Insert(tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := a.Claims().All(tx)
	if err != nil {
		t.Fatal(err)
	}

	bFound, cFound := false, false
	for _, v := range check {
		if v.TradeCategoryID == b.TradeCategoryID {
			bFound = true
		}
		if v.TradeCategoryID == c.TradeCategoryID {
			cFound = true
		}
	}

	if !bFound {
		t.Error("expected to find b")
	}
	if !cFound {
		t.Error("expected to find c")
	}

	slice := TradeCategorySlice{&a}
	if err = a.L.LoadClaims(tx, false, (*[]*TradeCategory)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.Claims); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	a.R.Claims = nil
	if err = a.L.LoadClaims(tx, true, &a, nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.Claims); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	if t.Failed() {
		t.Logf("%#v", check)
	}
}

func testTradeCategoryToManyTrades(t *testing.T) {
	var err error

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()

	var a TradeCategory
	var b, c Trade

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, tradeCategoryDBTypes, true, tradeCategoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TradeCategory struct: %s", err)
	}

	if err := a.Insert(tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = randomize.Struct(seed, &b, tradeDBTypes, false, tradeColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, tradeDBTypes, false, tradeColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}

	b.TradeCategoryID = a.ID
	c.TradeCategoryID = a.ID

	if err = b.Insert(tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := a.Trades().All(tx)
	if err != nil {
		t.Fatal(err)
	}

	bFound, cFound := false, false
	for _, v := range check {
		if v.TradeCategoryID == b.TradeCategoryID {
			bFound = true
		}
		if v.TradeCategoryID == c.TradeCategoryID {
			cFound = true
		}
	}

	if !bFound {
		t.Error("expected to find b")
	}
	if !cFound {
		t.Error("expected to find c")
	}

	slice := TradeCategorySlice{&a}
	if err = a.L.LoadTrades(tx, false, (*[]*TradeCategory)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.Trades); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	a.R.Trades = nil
	if err = a.L.LoadTrades(tx, true, &a, nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.Trades); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	if t.Failed() {
		t.Logf("%#v", check)
	}
}

func testTradeCategoryToManyAddOpClaims(t *testing.T) {
	var err error

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()

	var a TradeCategory
	var b, c, d, e Claim

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, tradeCategoryDBTypes, false, strmangle.SetComplement(tradeCategoryPrimaryKeyColumns, tradeCategoryColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*Claim{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, claimDBTypes, false, strmangle.SetComplement(claimPrimaryKeyColumns, claimColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	foreignersSplitByInsertion := [][]*Claim{
		{&b, &c},
		{&d, &e},
	}

	for i, x := range foreignersSplitByInsertion {
		err = a.AddClaims(tx, i != 0, x...)
		if err != nil {
			t.Fatal(err)
		}

		first := x[0]
		second := x[1]

		if a.ID != first.TradeCategoryID {
			t.Error("foreign key was wrong value", a.ID, first.TradeCategoryID)
		}
		if a.ID != second.TradeCategoryID {
			t.Error("foreign key was wrong value", a.ID, second.TradeCategoryID)
		}

		if first.R.TradeCategory != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}
		if second.R.TradeCategory != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}

		if a.R.Claims[i*2] != first {
			t.Error("relationship struct slice not set to correct value")
		}
		if a.R.Claims[i*2+1] != second {
			t.Error("relationship struct slice not set to correct value")
		}

		count, err := a.Claims().Count(tx)
		if err != nil {
			t.Fatal(err)
		}
		if want := int64((i + 1) * 2); count != want {
			t.Error("want", want, "got", count)
		}
	}
}
func testTradeCategoryToManyAddOpTrades(t *testing.T) {
	var err error

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()

	var a TradeCategory
	var b, c, d, e Trade

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, tradeCategoryDBTypes, false, strmangle.SetComplement(tradeCategoryPrimaryKeyColumns, tradeCategoryColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*Trade{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, tradeDBTypes, false, strmangle.SetComplement(tradePrimaryKeyColumns, tradeColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	foreignersSplitByInsertion := [][]*Trade{
		{&b, &c},
		{&d, &e},
	}

	for i, x := range foreignersSplitByInsertion {
		err = a.AddTrades(tx, i != 0, x...)
		if err != nil {
			t.Fatal(err)
		}

		first := x[0]
		second := x[1]

		if a.ID != first.TradeCategoryID {
			t.Error("foreign key was wrong value", a.ID, first.TradeCategoryID)
		}
		if a.ID != second.TradeCategoryID {
			t.Error("foreign key was wrong value", a.ID, second.TradeCategoryID)
		}

		if first.R.TradeCategory != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}
		if second.R.TradeCategory != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}

		if a.R.Trades[i*2] != first {
			t.Error("relationship struct slice not set to correct value")
		}
		if a.R.Trades[i*2+1] != second {
			t.Error("relationship struct slice not set to correct value")
		}

		count, err := a.Trades().Count(tx)
		if err != nil {
			t.Fatal(err)
		}
		if want := int64((i + 1) * 2); count != want {
			t.Error("want", want, "got", count)
		}
	}
}

func testTradeCategoriesReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &TradeCategory{}
	if err = randomize.Struct(seed, o, tradeCategoryDBTypes, true, tradeCategoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TradeCategory struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(tx); err != nil {
		t.Error(err)
	}
}

func testTradeCategoriesReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &TradeCategory{}
	if err = randomize.Struct(seed, o, tradeCategoryDBTypes, true, tradeCategoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TradeCategory struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := TradeCategorySlice{o}

	if err = slice.ReloadAll(tx); err != nil {
		t.Error(err)
	}
}

func testTradeCategoriesSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &TradeCategory{}
	if err = randomize.Struct(seed, o, tradeCategoryDBTypes, true, tradeCategoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TradeCategory struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := TradeCategories().All(tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	tradeCategoryDBTypes = map[string]string{`ID`: `int`, `Name`: `varchar`, `IsActive`: `bit`, `IsDeleted`: `bit`, `Created`: `datetime`, `Updated`: `datetime`}
	_                    = bytes.MinRead
)

func testTradeCategoriesUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(tradeCategoryPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(tradeCategoryAllColumns) == len(tradeCategoryPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &TradeCategory{}
	if err = randomize.Struct(seed, o, tradeCategoryDBTypes, true, tradeCategoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TradeCategory struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := TradeCategories().Count(tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, tradeCategoryDBTypes, true, tradeCategoryPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize TradeCategory struct: %s", err)
	}

	if rowsAff, err := o.Update(tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testTradeCategoriesSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(tradeCategoryAllColumns) == len(tradeCategoryPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &TradeCategory{}
	if err = randomize.Struct(seed, o, tradeCategoryDBTypes, true, tradeCategoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TradeCategory struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := TradeCategories().Count(tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, tradeCategoryDBTypes, true, tradeCategoryPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize TradeCategory struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(tradeCategoryAllColumns, tradeCategoryPrimaryKeyColumns) {
		fields = tradeCategoryAllColumns
	} else {
		fields = strmangle.SetComplement(
			tradeCategoryAllColumns,
			tradeCategoryPrimaryKeyColumns,
		)
		fields = strmangle.SetComplement(
			fields,
			tradeCategoryColumnsWithAuto,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := TradeCategorySlice{o}
	if rowsAff, err := slice.UpdateAll(tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testTradeCategoriesUpsert(t *testing.T) {
	t.Parallel()

	if len(tradeCategoryAllColumns) == len(tradeCategoryPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := TradeCategory{}
	if err = randomize.Struct(seed, &o, tradeCategoryDBTypes, true); err != nil {
		t.Errorf("Unable to randomize TradeCategory struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert TradeCategory: %s", err)
	}

	count, err := TradeCategories().Count(tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, tradeCategoryDBTypes, false, tradeCategoryPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize TradeCategory struct: %s", err)
	}

	if err = o.Upsert(tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert TradeCategory: %s", err)
	}

	count, err = TradeCategories().Count(tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
